send error message to stderr

diff --git a/files/usr/bin/vpn-route-fetch b/files/usr/bin/vpn-route-fetch
--- a/files/usr/bin/vpn-route-fetch
+++ b/files/usr/bin/vpn-route-fetch
@@ -22,7 +22,7 @@ if [ -n "$uplink" ]; then
 fi
 
 if ! addrs="$(resolveip "$dest")"; then
-	echo "failed to look up \"$dest\""
+	echo "failed to look up \"$dest\"" >&2
 	exit 2
 fi
 
